nelmio_cors:
    defaults:
        origin_regex: true
        # Explicitly allow local front-end origins
        allow_origin: ['^http://localhost(:[0-9]+)?$', '^http://127\.0\.0\.1(:[0-9]+)?$']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
        expose_headers: ['Link']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/': null
